"""Route inventory for mutating-route fuzz tests.

This module contains ROUTE_TABLE — a Python tuple of dicts derived from
.omc/route-inventory.json — so the fuzz test file does not depend on
external JSON files at runtime.

Each entry has keys:
  path           — URL path (Litestar template syntax, e.g. {id:str})
  method         — HTTP verb (POST / PUT / DELETE)
  handler_module — vetinari module that owns the handler
  handler_symbol — function name in that module
  auth_required  — "required" or "none"
  body_schema    — "dict", "none", or "file-upload"
  key_fields     — list of required body field names
  known_repros   — list of human-readable repro descriptions

The extra entry for /api/v1/training/data/upload is not in the JSON
inventory but exists in litestar_training_experiments_api.py and is
required by SESSION-32.3 coverage.
"""

from __future__ import annotations

# -- Route table: derived from .omc/route-inventory.json + one manual addition --
# Who writes: maintainers (regenerate via session plan tooling)
# Who reads:  tests/runtime/test_mutating_route_fuzz.py
# Lifecycle:  updated whenever routes change in vetinari/web/
# Lock:       not needed (read-only at import time)

ROUTE_TABLE: tuple[dict, ...] = (
    {
        "path": "/api/v1/approvals/{action_id}/approve",
        "method": "POST",
        "handler_module": "vetinari.web.approvals_api",
        "handler_symbol": "approve_action",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["reason"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/approvals/{action_id}/reject",
        "method": "POST",
        "handler_module": "vetinari.web.approvals_api",
        "handler_symbol": "reject_action",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": ["reason"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/autonomy/promote/{action_type}",
        "method": "POST",
        "handler_module": "vetinari.web.approvals_api",
        "handler_symbol": "apply_promotion",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/autonomy/veto/{action_type}",
        "method": "POST",
        "handler_module": "vetinari.web.approvals_api",
        "handler_symbol": "veto_promotion",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/autonomy/veto/{action_type}",
        "method": "DELETE",
        "handler_module": "vetinari.web.approvals_api",
        "handler_symbol": "clear_veto",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/admin/credentials/{source_type}",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_admin_routes",
        "handler_symbol": "api_admin_set_credential",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/admin/credentials/{source_type}/rotate",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_admin_routes",
        "handler_symbol": "api_admin_rotate_credential",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/admin/credentials/{source_type}",
        "method": "DELETE",
        "handler_module": "vetinari.web.litestar_admin_routes",
        "handler_symbol": "api_admin_delete_credential",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/adr",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_adr_routes",
        "handler_symbol": "api_adr_create",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["title"],
        "known_repros": [],
    },
    {
        "path": "/api/adr/{adr_id}",
        "method": "PUT",
        "handler_module": "vetinari.web.litestar_adr_routes",
        "handler_symbol": "api_adr_update",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["replacement_id"],
        "known_repros": [],
    },
    {
        "path": "/api/adr/{adr_id}/deprecate",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_adr_routes",
        "handler_symbol": "api_adr_deprecate",
        "auth_required": "required",
        "body_schema": "dict",
        # replacement_id is explicitly nullable — null means "no replacement ADR".
        # The handler rejects an empty body but accepts {"replacement_id": null}.
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/adr/propose",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_adr_routes",
        "handler_symbol": "api_adr_propose",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [
            "POST /api/adr/propose with object num_options -> 500 (should be 422)",
        ],
    },
    {
        "path": "/api/adr/propose/accept",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_adr_routes",
        "handler_symbol": "api_adr_propose_accept",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/adr/from-plan",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_adr_routes",
        "handler_symbol": "api_add_adr_from_plan",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["adr_id", "title", "context", "decision"],
        "known_repros": [],
    },
    {
        "path": "/api/adr/{adr_id}/link-plan",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_adr_routes",
        "handler_symbol": "api_adr_link_plan",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/agents/initialize",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_agents_api",
        "handler_symbol": "api_agents_initialize",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/decisions",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_agents_api",
        "handler_symbol": "api_decisions_submit",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": ["decision_id", "choice"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/analytics/sla/breach",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_analytics",
        "handler_symbol": "record_sla_breach",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": ["slo_name", "value", "budget"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/a2a",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_app",
        "handler_symbol": "handle_a2a_request",
        "auth_required": "none",
        "body_schema": "dict",
        "key_fields": ["id"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/a2a/raw",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_app",
        "handler_symbol": "handle_a2a_request_raw",
        "auth_required": "none",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/autonomy/policies/{action_type}",
        "method": "PUT",
        "handler_module": "vetinari.web.litestar_autonomy_api",
        "handler_symbol": "update_policy",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["level", "description"],
        "known_repros": [
            "PUT /api/v1/autonomy/policies/<action_type> with list description -> accepts (should 422)",
            "PUT /api/v1/autonomy/policies/<action_type> with dict description -> accepts (should 422)",
        ],
    },
    {
        "path": "/api/v1/autonomy/promotions/{action_type}/veto",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_autonomy_api",
        "handler_symbol": "veto_promotion",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/undo/{action_id}",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_autonomy_api",
        "handler_symbol": "undo_action",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/chat/attachments",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_chat_api",
        "handler_symbol": "upload_attachment",
        "auth_required": "required",
        "body_schema": "file-upload",
        "key_fields": [],
        "known_repros": [
            "POST /api/v1/chat/attachments with real multipart -> 500 (should be 200 or 422)",
        ],
    },
    {
        "path": "/api/v1/chat/feedback",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_chat_api",
        "handler_symbol": "submit_feedback",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["project_id", "task_id", "rating", "score", "comment"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/chat/retry/{project_id}/{task_id}",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_chat_api",
        "handler_symbol": "retry_task",
        "auth_required": "required",
        "body_schema": "dict",
        # model is explicitly nullable — null means "use project default model".
        # The RetryTaskRequest struct requires the field to be present but accepts null.
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/dashboard/quality/batch",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_dashboard_api",
        "handler_symbol": "api_record_quality_batch",
        "auth_required": "none",
        "body_schema": "none",
        "key_fields": ["quality_scores"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/dashboard/quality/scores-batch",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_dashboard_api",
        "handler_symbol": "api_dashboard_quality_scores_batch",
        "auth_required": "none",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/traces",
        "method": "DELETE",
        "handler_module": "vetinari.web.litestar_dashboard_metrics",
        "handler_symbol": "delete_all_traces",
        "auth_required": "none",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/decomposition/decompose",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_decomposition_routes",
        "handler_symbol": "api_decomposition_decompose",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/decomposition/decompose-agent",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_decomposition_routes",
        "handler_symbol": "api_decomposition_decompose_agent",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["plan_id"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/workflow/gates/{stage}",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_manufacturing_api",
        "handler_symbol": "api_add_gate",
        "auth_required": "none",
        "body_schema": "dict",
        "key_fields": ["name", "criteria", "failure_action"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/workflow/gates/{stage}",
        "method": "PUT",
        "handler_module": "vetinari.web.litestar_manufacturing_api",
        "handler_symbol": "api_workflow_gate_add",
        "auth_required": "none",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/workflow/gates/{stage}",
        "method": "DELETE",
        "handler_module": "vetinari.web.litestar_manufacturing_api",
        "handler_symbol": "api_remove_gate",
        "auth_required": "none",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/mcp/message",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_mcp_transport",
        "handler_symbol": "handle_mcp_message",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/memory",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_memory_api",
        "handler_symbol": "store_memory",
        "auth_required": "none",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [
            "POST /api/v1/memory with null content -> 500 (should be 422)",
        ],
    },
    {
        "path": "/api/v1/memory/{entry_id}",
        "method": "PUT",
        "handler_module": "vetinari.web.litestar_memory_api",
        "handler_symbol": "update_memory",
        "auth_required": "none",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [
            "PUT /api/v1/memory/{entry_id} with null content -> 500 (should be 422)",
        ],
    },
    {
        "path": "/api/v1/memory/{entry_id}",
        "method": "DELETE",
        "handler_module": "vetinari.web.litestar_memory_api",
        "handler_symbol": "forget_memory",
        "auth_required": "none",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/milestones/approve",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_milestones_api",
        "handler_symbol": "submit_milestone_approval",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": ["action"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/models/assign-tasks",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_model_mgmt",
        "handler_symbol": "assign_tasks_to_models",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": ["tasks"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/models",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_model_mgmt",
        "handler_symbol": "add_model",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": ["model_id"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/models/{model_id}/delete",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_model_mgmt",
        "handler_symbol": "remove_model",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/models/chat-stream",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_model_mgmt",
        "handler_symbol": "chat_stream",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/vram/phase",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_model_mgmt",
        "handler_symbol": "vram_set_phase",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [
            "POST /api/v1/vram/phase with list phase -> 500 TypeError: unhashable (should be 422)",
        ],
    },
    {
        "path": "/api/v1/models/cascade-router/build",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_model_mgmt",
        "handler_symbol": "build_cascade_from_router",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [
            "POST /api/v1/models/cascade-router/build with list confidence_threshold -> 500 (should be 422)",
        ],
    },
    {
        "path": "/api/v1/models/cascade/disable",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_model_mgmt",
        "handler_symbol": "cascade_disable",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/models/select",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_models_catalog",
        "handler_symbol": "api_model_select",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["task_type", "context"],
        "known_repros": [
            "POST /api/v1/models/select with empty body -> 201 (should be 422)",
        ],
    },
    {
        "path": "/api/v1/models/policy",
        "method": "PUT",
        "handler_module": "vetinari.web.litestar_models_catalog",
        "handler_symbol": "api_model_policy_update",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/models/reload",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_models_catalog",
        "handler_symbol": "api_models_reload",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/models/search",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_models_catalog",
        "handler_symbol": "api_global_model_search",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [
            "POST /api/v1/models/search with dict query -> 500 (.strip()) (should be 422)",
        ],
    },
    {
        "path": "/api/v1/models/download",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_models_catalog",
        "handler_symbol": "api_model_download",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [
            "POST /api/v1/models/download with dict repo_id -> 500 (should be 422)",
            "POST /api/v1/models/download with list filename -> 500 (should be 422)",
        ],
    },
    {
        "path": "/api/v1/models/refresh",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_models_discovery",
        "handler_symbol": "api_models_refresh",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/score-models",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_models_discovery",
        "handler_symbol": "api_score_models",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [
            "POST /api/v1/score-models with list task_description -> 500 (.lower()) (should be 422)",
        ],
    },
    {
        "path": "/api/v1/model-config",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_models_discovery",
        "handler_symbol": "api_update_model_config",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [
            "default_models",
            "fallback_models",
            "uncensored_fallback_models",
            "memory_budget_gb",
            "project_id",
        ],
        "known_repros": [
            "POST /api/v1/model-config with list memory_budget_gb -> 500 (int()) (should be 422)",
        ],
    },
    {
        "path": "/api/v1/swap-model",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_models_discovery",
        "handler_symbol": "api_swap_model",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["project_id"],
        "known_repros": [
            "POST /api/v1/swap-model with list project_id -> 500 (should be 422)",
        ],
    },
    {
        "path": "/api/plan/generate",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_plan_api",
        "handler_symbol": "generate_plan",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": ["domain_hint"],
        "known_repros": [],
    },
    {
        "path": "/api/plan/{plan_id}/approve",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_plan_api",
        "handler_symbol": "approve_plan",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": ["audit_id", "risk_score", "timestamp"],
        "known_repros": [],
    },
    {
        "path": "/api/coding/task",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_plan_api",
        "handler_symbol": "create_coding_task",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/coding/multi-step",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_plan_api",
        "handler_symbol": "create_multi_step_coding",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/plan",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_plans_api",
        "handler_symbol": "api_create_plan",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/plans",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_plans_api",
        "handler_symbol": "api_plan_create",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["waves"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/plans/{plan_id}",
        "method": "PUT",
        "handler_module": "vetinari.web.litestar_plans_api",
        "handler_symbol": "api_plan_update",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/plans/{plan_id}",
        "method": "DELETE",
        "handler_module": "vetinari.web.litestar_plans_api",
        "handler_symbol": "api_plan_delete",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/ponder/choose-model",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_ponder_routes",
        "handler_symbol": "api_ponder_choose_model",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/ponder/plan/{plan_id}",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_ponder_routes",
        "handler_symbol": "api_ponder_run_plan",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/project/git/commit-message",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_project_git",
        "handler_symbol": "project_git_commit_message",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": ["description", "scope"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/project/git/conflicts",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_project_git",
        "handler_symbol": "project_git_conflicts",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": ["target_branch"],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/rename",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_rename_project",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [
            "POST /api/project/{project_id}/rename with object description -> 500 (should be 422)",
        ],
    },
    {
        "path": "/api/project/{project_id}/archive",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_archive_project",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}",
        "method": "DELETE",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_delete_project",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/new-project",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_new_project",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/task",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_add_task",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/message",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_project_message",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/execute",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_project_execute",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["task_id"],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/verify-goal",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_verify_goal",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/approve",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_approve_outputs",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/assemble",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_project_assemble",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/merge",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_merge_project",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/files/read",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_read_file",
        "auth_required": "none",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/files/write",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_write_file",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/model-search",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_model_search",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/cancel",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_execution",
        "handler_symbol": "api_cancel_project",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/pause",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_execution",
        "handler_symbol": "api_pause_project",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/resume",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_execution",
        "handler_symbol": "api_resume_project",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/project/{project_id}/refresh-models",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_projects_api",
        "handler_symbol": "api_refresh_project_models",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [
            "POST /api/project/{project_id}/refresh-models with nonexistent project -> 201 (should be 404)",
        ],
    },
    {
        "path": "/api/v1/replay",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_replay_api",
        "handler_symbol": "replay_pipeline",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": ["overrides"],
        "known_repros": [
            "POST /api/v1/replay with list overrides -> 500 (should be 422)",
        ],
    },
    {
        "path": "/api/v1/rules/global",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_rules_routes",
        "handler_symbol": "api_rules_global_post",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/rules/global-prompt",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_rules_routes",
        "handler_symbol": "api_rules_global_prompt_post",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/rules/project/{project_id}",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_rules_routes",
        "handler_symbol": "api_rules_project_post",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/rules/model/{model_id}",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_rules_routes",
        "handler_symbol": "api_rules_model_post",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/sandbox/execute",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_sandbox_api",
        "handler_symbol": "api_sandbox_execute",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["code", "context"],
        "known_repros": [],
    },
    {
        "path": "/api/sandbox/plugins/hook",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_sandbox_api",
        "handler_symbol": "api_plugin_execute_hook",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/search/index",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_search_api",
        "handler_symbol": "api_search_index",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["project_path"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/skills/{skill_id}/validate",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_skills_api",
        "handler_symbol": "validate_output",
        "auth_required": "none",
        "body_schema": "dict",
        "key_fields": ["output"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/skills/propose",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_skills_api",
        "handler_symbol": "propose_skill",
        "auth_required": "none",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/subtasks/{plan_id}",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_subtasks_api",
        "handler_symbol": "api_create_subtask",
        "auth_required": "none",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/subtasks/{plan_id}/{subtask_id}",
        "method": "PUT",
        "handler_module": "vetinari.web.litestar_subtasks_api",
        "handler_symbol": "api_update_subtask",
        "auth_required": "none",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/assignments/execute-pass",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_subtasks_api",
        "handler_symbol": "api_assignment_execute_pass",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["plan_id"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/system-prompts",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_system_content",
        "handler_symbol": "api_save_system_prompt",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["name"],
        "known_repros": [
            "POST /api/v1/system-prompts normalizes '..' name to 'unnamed' (should 400)",
        ],
    },
    {
        "path": "/api/v1/system-prompts/{name}",
        "method": "DELETE",
        "handler_module": "vetinari.web.litestar_system_content",
        "handler_symbol": "api_delete_system_prompt",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [
            "DELETE /api/v1/system-prompts/{name} normalizes '%2E%2E'/'%5C' to safe name (should 400)",
        ],
    },
    {
        "path": "/api/v1/preferences",
        "method": "PUT",
        "handler_module": "vetinari.web.litestar_system_content",
        "handler_symbol": "api_set_preferences",
        "auth_required": "none",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/settings",
        "method": "PUT",
        "handler_module": "vetinari.web.litestar_system_content",
        "handler_symbol": "api_update_settings",
        "auth_required": "none",
        "body_schema": "dict",
        "key_fields": ["inference", "agent_timeouts", "log_level"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/variant",
        "method": "PUT",
        "handler_module": "vetinari.web.litestar_system_content",
        "handler_symbol": "api_set_variant",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["level"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/server/shutdown",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_system_hardware",
        "handler_symbol": "api_server_shutdown",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/system/vram/phase",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_system_hardware",
        "handler_symbol": "api_set_vram_phase",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["phase"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/config",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_system_status",
        "handler_symbol": "api_config_post",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/config",
        "method": "PUT",
        "handler_module": "vetinari.web.litestar_system_status",
        "handler_symbol": "api_config_put",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["path"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/validate-path",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_system_status",
        "handler_symbol": "api_validate_path",
        "auth_required": "none",
        "body_schema": "dict",
        "key_fields": ["path"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/browse-directory",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_system_status",
        "handler_symbol": "api_browse_directory",
        "auth_required": "none",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/run-task",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_tasks_api",
        "handler_symbol": "api_run_task",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["task_id"],
        "known_repros": [
            "POST /api/v1/run-task with dict task_id -> 201 (should be 422)",
        ],
    },
    {
        "path": "/api/v1/run-all",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_tasks_api",
        "handler_symbol": "api_run_all",
        "auth_required": "required",
        "body_schema": "none",  # handler accepts no body: data: dict | None = None
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/run-prompt",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_tasks_api",
        "handler_symbol": "api_run_prompt",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [
            "POST /api/v1/run-prompt with null prompt -> 500 (should be 422)",
        ],
    },
    {
        "path": "/api/v1/training/start",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_training_api",
        "handler_symbol": "training_start",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": ["skill"],
        "known_repros": [],
    },
    {
        "path": "/api/v1/training/pause",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_training_api_part2",
        "handler_symbol": "training_pause",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/training/resume",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_training_api_part2",
        "handler_symbol": "training_resume",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/training/stop",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_training_api_part2",
        "handler_symbol": "training_stop",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/training/data/seed",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_training_api_part2",
        "handler_symbol": "training_data_seed",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/training/dry-run",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_training_api_part3",
        "handler_symbol": "training_dry_run",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/training/rules",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_training_api_part3",
        "handler_symbol": "training_rules_set",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/training/sync-data",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_training_api_part3",
        "handler_symbol": "training_sync_data",
        "auth_required": "required",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/training/generate-synthetic",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_training_api_part3",
        "handler_symbol": "training_generate_synthetic",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/v1/training/experiments/compare",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_training_experiments_api",
        "handler_symbol": "compare_experiments",
        "auth_required": "none",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [
            "POST /api/v1/training/experiments/compare with dict in experiment_ids -> 500 (should be 422)",
        ],
    },
    # Extra entry: exists in litestar_training_experiments_api.py but absent from
    # the JSON inventory.  SESSION-32.3 explicitly requires testing it.
    {
        "path": "/api/v1/training/data/upload",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_training_experiments_api",
        "handler_symbol": "upload_training_data",
        "auth_required": "required",
        "body_schema": "file-upload",
        "key_fields": [],
        "known_repros": [
            "POST /api/v1/training/data/upload with real multipart -> 500 (should be 200 or 422)",
        ],
    },
    {
        "path": "/api/generate-image",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_training_routes",
        "handler_symbol": "api_generate_image",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/training/export",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_training_routes",
        "handler_symbol": "api_training_export",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/training/start",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_training_routes",
        "handler_symbol": "api_training_start",
        "auth_required": "required",
        "body_schema": "dict",
        "key_fields": [],
        "known_repros": [],
    },
    {
        "path": "/api/plans/{plan_id}/approve-gate",
        "method": "POST",
        "handler_module": "vetinari.web.litestar_visualization",
        "handler_symbol": "api_approve_gate",
        "auth_required": "none",
        "body_schema": "none",
        "key_fields": [],
        "known_repros": [],
    },
)
