"""
Vetinari Coding Agent - In-process coding agent for code generation.

This module provides:
- CodeAgentEngine: In-process coding agent using internal LM
- CodeTask, CodeArtifact: Data models for coding tasks
- Integration with DualMemoryStore for provenance
"""

import os
import logging
import uuid
import json
import time
from dataclasses import dataclass, field, asdict
from typing import List, Optional, Dict, Any, Union
from datetime import datetime
from enum import Enum

logger = logging.getLogger(__name__)


from vetinari.types import CodingTaskType, CodingTaskStatus  # canonical enums


class ArtifactType(str, Enum):
    """Types of code artifacts."""
    PATCH = "patch"
    FILE_CONTENTS = "file_contents"
    BUILD_ARTIFACT = "build_artifact"
    TEST_ARTIFACT = "test_artifact"


@dataclass
class CodeTask:
    """A coding task to be executed by the coding agent."""
    task_id: str = field(default_factory=lambda: f"code_{uuid.uuid4().hex[:8]}")
    plan_id: str = ""
    subtask_id: str = ""
    type: CodingTaskType = CodingTaskType.SCAFFOLD
    language: str = "python"
    framework: str = ""
    repo_path: str = ""
    target_files: List[str] = field(default_factory=list)
    constraints: Union[str, List[str]] = ""
    description: str = ""
    status: CodingTaskStatus = CodingTaskStatus.PENDING
    rationale: str = ""
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    updated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    
    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        if isinstance(self.type, CodingTaskType):
            data["type"] = self.type.value
        if isinstance(self.status, CodingTaskStatus):
            data["status"] = self.status.value
        return data
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'CodeTask':
        if "type" in data and isinstance(data["type"], str):
            data["type"] = CodingTaskType(data["type"])
        if "status" in data and isinstance(data["status"], str):
            data["status"] = CodingTaskStatus(data["status"])
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


@dataclass
class CodeArtifact:
    """A code artifact generated by the coding agent."""
    artifact_id: str = field(default_factory=lambda: f"art_{uuid.uuid4().hex[:8]}")
    task_id: str = ""
    type: ArtifactType = ArtifactType.FILE_CONTENTS
    path: str = ""
    content: str = ""
    diff: str = ""
    provenance: str = ""
    language: str = "python"
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    
    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        if isinstance(self.type, ArtifactType):
            data["type"] = self.type.value
        return data
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'CodeArtifact':
        if "type" in data and isinstance(data["type"], str):
            data["type"] = ArtifactType(data["type"])
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


class CodeAgentEngine:
    """In-process coding agent engine.
    
    This MVP uses an internal LM wrapper to draft code.
    It can also delegate to an external bridge for heavier tasks.
    """
    
    def __init__(self, lm_provider: str = "internal"):
        self.lm_provider = lm_provider
        self.enabled = os.environ.get("CODING_AGENT_ENABLED", "true").lower() in ("1", "true", "yes")
        self.use_bridge = os.environ.get("CODING_AGENT_USE_BRIDGE", "false").lower() in ("1", "true", "yes")
        self.bridge_endpoint = os.environ.get("CODING_BRIDGE_ENDPOINT", "http://localhost:4096")
        
        logger.info("CodeAgentEngine initialized (provider=%s, enabled=%s, bridge=%s)", lm_provider, self.enabled, self.use_bridge)
    
    def is_available(self) -> bool:
        """Check if the coding agent is available."""
        return self.enabled
    
    def run_task(self, task: CodeTask) -> CodeArtifact:
        """Execute a coding task and return an artifact.
        
        This MVP implementation:
        1. Uses internal LM for simple tasks (scaffold, tiny modules)
        2. Can delegate to external bridge for complex tasks
        """
        if not self.enabled:
            raise RuntimeError("Coding agent is not enabled")
        
        task.status = CodingTaskStatus.IN_PROGRESS
        task.updated_at = datetime.now().isoformat()
        
        logger.info("Executing coding task: %s (%s)", task.task_id, task.type.value)
        
        try:
            if self.use_bridge:
                artifact = self._run_via_bridge(task)
            else:
                artifact = self._run_in_process(task)
            
            task.status = CodingTaskStatus.COMPLETED
            task.updated_at = datetime.now().isoformat()
            
            return artifact
            
        except Exception as e:
            logger.error("Coding task failed: %s", e)
            task.status = CodingTaskStatus.FAILED
            task.updated_at = datetime.now().isoformat()
            raise
    
    def _run_in_process(self, task: CodeTask) -> CodeArtifact:
        """Run task using AdapterManager (LLM-powered) with template fallback."""
        # Try LLM-powered generation first
        llm_result = self._generate_via_llm(task)
        if llm_result:
            return llm_result

        # Fallback to template stubs
        if task.type == CodingTaskType.SCAFFOLD:
            return self._generate_scaffold(task)
        elif task.type == CodingTaskType.IMPLEMENT:
            return self._generate_implementation(task)
        elif task.type == CodingTaskType.TEST:
            return self._generate_tests(task)
        elif task.type == CodingTaskType.REVIEW:
            return self._generate_review(task)
        else:
            return self._generate_generic(task)

    def _generate_via_llm(self, task: CodeTask) -> Optional["CodeArtifact"]:
        """Generate code using the LLM via AdapterManager."""
        try:
            from vetinari.adapter_manager import get_adapter_manager

            constraints_str = (
                ", ".join(task.constraints) if isinstance(task.constraints, list)
                else task.constraints
            )
            target = task.target_files[0] if task.target_files else "output.py"

            prompts = {
                CodingTaskType.SCAFFOLD: (
                    f"Generate a complete {task.language} project scaffold for: {task.description}. "
                    f"Framework: {task.framework or 'standard library'}. "
                    f"Target file: {target}. "
                    f"Constraints: {constraints_str or 'none'}. "
                    "Return ONLY the code, no explanations."
                ),
                CodingTaskType.IMPLEMENT: (
                    f"Implement the following in {task.language}: {task.description}. "
                    f"Target file: {target}. "
                    f"Constraints: {constraints_str or 'none'}. "
                    "Return ONLY the complete implementation code."
                ),
                CodingTaskType.TEST: (
                    f"Write comprehensive unit tests in {task.language} for: {task.description}. "
                    f"Target: {target}. Use pytest. "
                    "Return ONLY the test code."
                ),
                CodingTaskType.REVIEW: (
                    f"Review this {task.language} code and provide actionable feedback: "
                    f"{task.description}. "
                    "Return a structured review with: issues, improvements, security concerns, rating."
                ),
                CodingTaskType.REFACTOR: (
                    f"Refactor the following {task.language} code to improve quality: "
                    f"{task.description}. "
                    "Return ONLY the refactored code."
                ),
                CodingTaskType.FIX: (
                    f"Fix the following bug in {task.language}: {task.description}. "
                    f"Target: {target}. "
                    "Return ONLY the fixed code."
                ),
                CodingTaskType.DOCUMENT: (
                    f"Write documentation for: {task.description}. "
                    "Return well-structured markdown documentation."
                ),
            }

            user_prompt = prompts.get(task.type, f"Complete this coding task: {task.description}")
            system_prompt = (
                f"You are an expert {task.language} developer. "
                f"Framework: {task.framework or 'none'}. "
                "Write clean, well-commented, production-quality code. "
                "Follow best practices and handle edge cases."
            )

            adapter_manager = get_adapter_manager()
            response = adapter_manager.infer(
                prompt=user_prompt,
                system_prompt=system_prompt,
                max_tokens=2048,
            )
            content = response.get("output", "").strip() if isinstance(response, dict) else str(response).strip()

            if not content:
                return None

            return CodeArtifact(
                artifact_id=f"art_{uuid.uuid4().hex[:8]}",
                task_id=task.task_id,
                type=ArtifactType.FILE_CONTENTS,
                path=f"{task.repo_path}/{target}" if task.repo_path else target,
                content=content,
                provenance="llm_generated",
                language=task.language,
            )
        except Exception as e:
            logger.debug("LLM code generation failed (will use fallback): %s", e)
            return None
    
    def _generate_scaffold(self, task: CodeTask) -> CodeArtifact:
        """Generate a Python package scaffold."""
        
        project_name = task.target_files[0].replace(".py", "") if task.target_files else "demo_project"
        
        scaffold_content = f'''"""
{project_name} - Auto-generated scaffold.
"""

__version__ = "0.1.0"
__author__ = "Vetinari Coding Agent"

def main():
    """Main entry point."""
    print("Hello from {project_name}!")

if __name__ == "__main__":
    main()
'''
        
        artifact = CodeArtifact(
            artifact_id=f"art_{uuid.uuid4().hex[:8]}",
            task_id=task.task_id,
            type=ArtifactType.FILE_CONTENTS,
            path=f"{task.repo_path}/{project_name}/__init__.py" if task.repo_path else f"{project_name}/__init__.py",
            content=scaffold_content,
            provenance="in_process_coder",
            language=task.language
        )
        
        logger.info("Generated scaffold for %s", project_name)
        return artifact
    
    def _generate_implementation(self, task: CodeTask) -> CodeArtifact:
        """Generate implementation code."""
        
        target = task.target_files[0] if task.target_files else "module.py"
        
        impl_content = f'''"""
Implementation for {target}
Generated by Vetinari Coding Agent
"""

class Implementation:
    """Main implementation class."""
    
    def __init__(self):
        self.data = {{}}
    
    def process(self, input_data):
        """Process input data."""
        return {{
            "status": "success",
            "data": input_data
        }}
'''
        
        artifact = CodeArtifact(
            artifact_id=f"art_{uuid.uuid4().hex[:8]}",
            task_id=task.task_id,
            type=ArtifactType.FILE_CONTENTS,
            path=f"{task.repo_path}/{target}" if task.repo_path else target,
            content=impl_content,
            provenance="in_process_coder",
            language=task.language
        )
        
        logger.info("Generated implementation for %s", target)
        return artifact
    
    def _generate_tests(self, task: CodeTask) -> CodeArtifact:
        """Generate unit tests."""
        
        target = task.target_files[0] if task.target_files else "module"
        test_content = f'''"""
Unit tests for {target}
Generated by Vetinari Coding Agent
"""

import pytest
from {target} import Implementation


class TestImplementation:
    """Test cases for Implementation class."""
    
    def test_process_returns_dict(self):
        """Test that process returns a dictionary."""
        impl = Implementation()
        result = impl.process("test input")
        assert isinstance(result, dict)
    
    def test_process_status_success(self):
        """Test that process returns success status."""
        impl = Implementation()
        result = impl.process("test input")
        assert result.get("status") == "success"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''
        
        artifact = CodeArtifact(
            artifact_id=f"art_{uuid.uuid4().hex[:8]}",
            task_id=task.task_id,
            type=ArtifactType.TEST_ARTIFACT,
            path=f"{task.repo_path}/test_{target}.py" if task.repo_path else f"test_{target}.py",
            content=test_content,
            provenance="in_process_coder",
            language=task.language
        )
        
        logger.info("Generated tests for %s", target)
        return artifact
    
    def _generate_review(self, task: CodeTask) -> CodeArtifact:
        """Generate a code review summary."""
        
        review_content = f'''# Code Review Summary

## Task: {task.task_id}
## Type: {task.type.value}

### Files Reviewed
{task.target_files}

### Constraints
{", ".join(task.constraints) if isinstance(task.constraints, list) else task.constraints}

### Notes
- Code follows Python style guidelines
- Basic error handling implemented
- Tests should be added for edge cases
'''
        
        artifact = CodeArtifact(
            artifact_id=f"art_{uuid.uuid4().hex[:8]}",
            task_id=task.task_id,
            type=ArtifactType.FILE_CONTENTS,
            path=f"{task.repo_path}/review.md" if task.repo_path else "review.md",
            content=review_content,
            provenance="in_process_coder",
            language="markdown"
        )
        
        logger.info("Generated review for %s", task.task_id)
        return artifact
    
    def _generate_generic(self, task: CodeTask) -> CodeArtifact:
        """Generate generic code for unspecified tasks."""
        
        content = f'''# Generated by Vetinari Coding Agent
# Task: {task.task_id}
# Type: {task.type.value}
# Language: {task.language}

{task.description or "No description provided."}
'''
        
        target = task.target_files[0] if task.target_files else "generated.py"
        
        artifact = CodeArtifact(
            artifact_id=f"art_{uuid.uuid4().hex[:8]}",
            task_id=task.task_id,
            type=ArtifactType.FILE_CONTENTS,
            path=f"{task.repo_path}/{target}" if task.repo_path else target,
            content=content,
            provenance="in_process_coder",
            language=task.language
        )
        
        return artifact
    
    def _run_via_bridge(self, task: CodeTask) -> CodeArtifact:
        """Run task via external bridge (placeholder)."""
        
        logger.info("Delegating task %s to external bridge at %s", task.task_id, self.bridge_endpoint)
        
        # Placeholder for external bridge integration
        # In production, this would make HTTP calls to the bridge service
        return self._run_in_process(task)
    
    def run_multi_step_task(self, tasks: List[CodeTask]) -> List[CodeArtifact]:
        """Run multiple coding tasks (scaffold + module + tests)."""
        
        artifacts = []
        
        for task in tasks:
            try:
                artifact = self.run_task(task)
                artifacts.append(artifact)
            except Exception as e:
                logger.error("Task %s failed: %s", task.task_id, e)
                if not self.use_bridge:
                    raise
        
        return artifacts


_coding_agent: Optional[CodeAgentEngine] = None


def get_coding_agent() -> CodeAgentEngine:
    """Get or create the global coding agent instance."""
    global _coding_agent
    if _coding_agent is None:
        _coding_agent = CodeAgentEngine()
    return _coding_agent


def init_coding_agent(lm_provider: str = "internal") -> CodeAgentEngine:
    """Initialize a new coding agent instance."""
    global _coding_agent
    _coding_agent = CodeAgentEngine(lm_provider=lm_provider)
    return _coding_agent
